
[target.aarch64-linux-android]
ar = "/Users/msalopek/Library/Android/sdk/ndk/28.0.12916984/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/msalopek/Library/Android/sdk/ndk/28.0.12916984/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"

[env]
CC_aarch64-linux-android = "/Users/msalopek/Library/Android/sdk/ndk/28.0.12916984/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"
CXX_aarch64-linux-android = "/Users/msalopek/Library/Android/sdk/ndk/28.0.12916984/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang++"
AR_aarch64-linux-android = "/Users/msalopek/Library/Android/sdk/ndk/28.0.12916984/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"


# iOS configuration
# [target.aarch64-apple-ios-sim]
# rustflags = [
#   "-C", "link-arg=-undefined",
#   "-C", "link-arg=dynamic_lookup",
# ]

# [target.aarch64-apple-ios]
# rustflags = [
#   "-C", "link-arg=-undefined",
#   "-C", "link-arg=dynamic_lookup",
# ]

# [target.aarch64-linux-android]
# ar = "/Users/peppi/Library/Android/sdk/ndk/28.0.12916984/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
# linker = "/Users/peppi/Library/Android/sdk/ndk/28.0.12916984/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"

# [env]
# CC_aarch64-linux-android = "/Users/peppi/Library/Android/sdk/ndk/28.0.12916984/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"
# CXX_aarch64-linux-android = "/Users/peppi/Library/Android/sdk/ndk/28.0.12916984/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang++"


# [target.aarch64-apple-ios]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# [target.aarch64-apple-ios-sim]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# [target.aarch64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
# Android configuration